#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/vps000 watch
	procd_set_param respawn 3600 10 0
	procd_close_instance
}

stop_service() {
	if [ "$VPS_KEEP_WANT" = "1" ]; then
		KEEP_WANT=1 /usr/sbin/vps000 disconnect >/dev/null 2>&1 || true
	else
		/usr/sbin/vps000 disconnect >/dev/null 2>&1 || true
	fi
}

restart() {
	VPS_KEEP_WANT=1
	export VPS_KEEP_WANT
	stop "$@"
	unset VPS_KEEP_WANT
	start "$@"
}
